### ISSUE TITLE
What's the difference between shawncplus/phpcomplete and phpcomplete-extended

### ISSUE THREAD

**Issue by markwu** [m2mdas/phpcomplete-extended#14]
Hi @m2mdas 

Would you kindly tell me what's the difference between shawncplus/phpcomplete and phpcomplete-extended? 

Can this two plugin works together?  Does this plugin support ctags for those quite old php project without composer? Does this project support namespace, triat and interface?

I try to read the scripts to find the answers, but no luck. :(

Mark

**Comment by m2mdas** [comment]
Hi @markwu 

I created this plugin after feeling the need of fast autocomplete solution for Vim. I previously used shawncplus's `phpcomlete` plugin, it kind of worked for small to medium projects but did not worked well for the large Symfony2 project I started working back then. As `phpcomplete` depends on `taglist()` method it is very slow at reading from ctags file of 10MB+ size. 

So I took different approach, for list of classmaps generated by composer I gathered information of the class by using `ReflectionClass`, `ReflectionMethod` and `ReflectionProperties` methods and parsing docblock comments via PHP and stored it as a index file and load it in Vim  after that. Index of core PHP classes are also added. As index is already loaded in Vim it provides fast autocompletion.

In this process I was also able to gather more information about the class e.g the class it extends, list of implemented class etc which is why you can list the classes that implements/extends a class. I also made the script pluggable so that it is possible to create index of framework related information, see [phpcomplete-exdended-laravel](https://github.com/m2mdas/phpcomplete-extended-laravel) and [phpcomplete-exdended-symfony](https://github.com/m2mdas/phpcomplete-extended-symfony) plugins for the implementation. I have also created a small parser to detect local variable types and provide autocomplete support for multi line expression. I have recently added support for array/ArrayAccess variable and has plans to add more autocomplete feature support. Currently it has support for interface, adding support of traits is in my TODO list. 

Currently the plugin only supports composer based projects but it is possible to create a plugin that reads file list from the ctags file and create autocomplete index for it. The feature is also in my TODO list.

Thanks for taking interest in my plugin.

**Comment by markwu** [comment]
HI @m2mdas 

Thanks for such detail response. I am very impressed about this plugin, it works very smart and well. The only constraint is it only works for those newer project.

I have bunch of old projects without composer support, so I have to switch between phpcomplete and phpcomplete-extended.

I will take some time to study this plugin to see if I can come out some indexers for my old project.

Thanks for this great tool.

BTW, I think your answer should list in FAQ section of front page.  It quite clear for those people want to know the difference between these two plugins.

**Comment by m2mdas** [comment]
Thanks for kind words. Glad you liked the plugin. I will add detailed FAQ section soon, I am also thinking about adding some gifs instead of the current youtube videos.

As for ctags support, `PSR0` convention of one class per file helped me building the plugin quickly. In non `PSR0` project multiple classes in one file is very common. For this reason there are some complexity in adding the feature. But rest assured, this feature have top priority in my TODO list. In the meantime you can use following snippet to switch between `phpcomplete` and `phpcomplete-extended`,

```
autocmd FileType php call SetOmniFunc()

function! SetOmniFunc() 
    if phpcomplete_extended#is_phpcomplete_extended_project()
        setlocal omnifunc=phpcomplete_extended#CompletePHP
    else
        setlocal omnifunc=phpcomplete#CompletePHP
    endif
endfunction
```
